using System;
using AutoItX3Lib;
using Microsoft.Extensions.Configuration;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using CrossMail.Tests.CrossoverHelper;
using Xunit;

namespace CrossMail.Tests
{
    /// <summary>
    /// Gmail Test Class
    /// </summary>
    public class GmailTests : IDisposable
    {
        /// <summary>
        /// IWebDriver Declaration
        /// </summary>
        readonly IWebDriver _browserDriver;

        /// <summary>
        /// IConfiguration Declaration
        /// </summary>
        readonly IConfiguration _config;

        /// <summary>
        /// TestReporting Class Local Object for this Test Class
        /// </summary>
        protected TestReporting testReporting;

        /// <summary>
        /// Constructor Method for Pre-Test Initialize Steps
        /// </summary>
        public GmailTests()
        {
            // Initializing TestReporting Class Object
            testReporting = new TestReporting();

            // TestReporting Test Created
            testReporting.CreateTest("ShouldSendEmail");

            _browserDriver = new ChromeDriver("./");
            testReporting.SetStepStatusPass("Chrome Driver started.");

            _config = new ConfigurationBuilder()
                .AddJsonFile("config.json")
                .Build();
            _browserDriver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(Convert.ToInt32(_config["_pageLoadTimeout"]));
            _browserDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(Convert.ToInt32(_config["_implicitWaitTimeSpan"]));
            testReporting.SetStepStatusPass("Json Config File Loaded Successfully.");
        }

        /// <summary>
        /// Dispose Method for Test Class
        /// </summary>
        public void Dispose()
        {
            // Reporting Test Case Result Status
            if(!SeleniumKeywordActions.FailedErrorStep)
                    testReporting.SetTestStatusPass();
            else
                    testReporting.SetTestStatusFail("Test Case Failed.");

            // Closing IWebDriver and Extent Test Report Object.
            _browserDriver.Quit();
            testReporting.Close();
        }

        /// <summary>
        /// Test Method - Fact - for Sending Email via Gmail Web Portal.
        /// </summary>
        [Fact]
        public void ShouldSendEmail()
        {
            // Navigate and launch the Gmail URL
            _browserDriver.LaunchUrl(testReporting, "https://mail.google.com/");
            _browserDriver.Manage().Window.Maximize();
            testReporting.SetStepStatusPass("BRowser Maximized.");

            // Enter the Username
            IWebElement userElement = _browserDriver.FindElement(By.Id(_config["_objectUserNameTextBox"]));
            userElement.SendKeys(testReporting, _config["username"], "User Name");

            // Click on the Next Button
            IWebElement nextButton = _browserDriver.FindElement(By.Id(_config["_objectUserNameNextButton"]));
            nextButton.Click(testReporting, "Username Next Button");

            // Enter the Password
            IWebElement passwordElement = _browserDriver.FindElement(By.Name(_config["_objectPasswordTextBox"]));
            if (passwordElement.Displayed && passwordElement.Enabled)
                passwordElement.Click(testReporting, "Password Text Box");

            passwordElement.SendKeys(testReporting, _config["password"], "Password Text Box");

            // Click on the Next Button
            nextButton = _browserDriver.FindElement(By.Id(_config["_objectUserPasswordNextButton"]));
            nextButton.Click(testReporting, "Password Next Button");

            // Click on the Compose Button
            IWebElement composeElement = _browserDriver.FindElement(By.XPath(_config["_objectComposeButton"]));
            composeElement.Click(testReporting, "Compose Email Button");

            // Enter the Recipient's Email Address
            IWebElement toElement = _browserDriver.FindElement(By.Name(_config["_objectToTextBox"]));
            toElement.Clear(testReporting, "Recipient's To Email Address Text Box");
            toElement.SendKeys(testReporting, $"{_config["username"]}@gmail.com", "Recipient's To Email Address Text Box");

            // Enter the Subject Line with Unique Date Time Stamp
            IWebElement subjectTextElement = _browserDriver.FindElement(By.Name(_config["objectSubjectTextBox"]));
            subjectTextElement.Clear(testReporting, "Subject Line Text Box");
            string subjectLineText = "Autogenerated Crossover Test User Email generated at " + DateTime.UtcNow.ToString();
            subjectTextElement.SendKeys(testReporting, subjectLineText, "Subject Line Text Box");

            // Enter the mail body text.
            string mailBodyText = "This is an Auto Generated Test Email.";
            IWebElement mailBodyElement = _browserDriver.FindElement(By.XPath(_config["objectMailBodyTextBox"]));
            mailBodyElement.Clear(testReporting, "Mail Body Text Box");
            mailBodyElement.SendKeys(testReporting, mailBodyText, "Mail Body Text Box");

            // Click on the More Options Button
            IWebElement moreOptionsElement = _browserDriver.FindElement(By.XPath(_config["objectMoreOptionsButton"]));
            moreOptionsElement.Click(testReporting, "More Options Button");

            // Click on the Labels Menu Item
            IWebElement labelMenuItemElement = _browserDriver.FindElement(By.XPath(_config["objectLabelMenuItem"]));
            labelMenuItemElement.Click(testReporting, "Label Menu Options Button");

            // Click and Add 'Social' Label to the Email
            IWebElement socialLabelElement = _browserDriver.FindElement(By.XPath(_config["objectSocialLabelMenuItem"]));
            socialLabelElement.Click(testReporting, "Social Label");

            // Add Attachment to the Mail
            _browserDriver.FindElement(By.XPath(_config["objectAttachFilesButton"])).Click();

            System.Threading.Thread.Sleep(5000);
            FileUpload(_config["_filePath"]);

            // Click on the Send Mail Button
            IWebElement sendButtonElement = _browserDriver.FindElement(By.XPath(_config["_objectSendMailButton"]));
            sendButtonElement.Click(testReporting, "Send Mail Button");

            // Validate and Click on the Message Sent Link Text
            IWebElement _messageSentLink = _browserDriver.FindElement(By.CssSelector(_config["_objectMessageSentLink"]));
            SeleniumKeywordActions.VerifyText(testReporting, _messageSentLink.Text, "View message", "'View message' Link");
            testReporting.SetStepStatusPass("Email Sent Successfully");

            System.Threading.Thread.Sleep(2000);

            // Click on the Social Label Inbox Tab
            IWebElement socialLabelInboxTab = _browserDriver.FindElement(By.XPath(_config["_objectSocialInboxElement"]));
            socialLabelInboxTab.Click(testReporting, "Social Label Inbox Tab");

            // Click on the Recieved Mail Row
            IWebElement mailElement = _browserDriver.FindElement(By.XPath(_config["_objectMailItem"]));
            mailElement.Click(testReporting, "Recieved Mail Row Element");

            System.Threading.Thread.Sleep(2000);

            // Test Case Validation Method Calls to Verify Sent Email's Label, Subject Line, Mail Body Text ad Attachment File Name.
            ProjectSpecificValidationHelper.ValidateSocialLabelElement(_browserDriver, testReporting);
            ProjectSpecificValidationHelper.ValidateSubjectLineTextElement(_browserDriver, testReporting, subjectLineText);
            ProjectSpecificValidationHelper.ValidateMailBodyTextElement(_browserDriver, testReporting, mailBodyText);
            ProjectSpecificValidationHelper.ValidateAttachmentNameTextElement(_browserDriver, testReporting, _config["_attachmentFileName"]);
            
        }

        /// <summary>
        /// Method for Uploading File from Windows Dialogue Box
        /// </summary>
        /// <param name="filePath">File Path String</param>
        private void FileUpload(string filePath)
        {
            AutoItX3 autoItX = new AutoItX3();
            autoItX.WinActivate("Open");
            autoItX.Send(filePath);
            System.Threading.Thread.Sleep(2000);
            autoItX.Send("{ENTER}");
            testReporting.SetStepStatusPass("File successfully attached with the mail.");
        }
    }
}