using AutoItX3Lib;
using Microsoft.Extensions.Configuration;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System;
using Xunit;

namespace CrossMail.Tests
{
    public class GmailTests : IDisposable
    {
        readonly IWebDriver _browserDriver;
        readonly IConfiguration _config;

        public GmailTests()
        {
            _browserDriver = new ChromeDriver("./");
            _config = new ConfigurationBuilder()
                .AddJsonFile("config.json")
                .Build();
            _browserDriver.Manage().Timeouts().PageLoad = TimeSpan.FromSeconds(Convert.ToInt32(_config["_pageLoadTimeout"]));
            _browserDriver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(Convert.ToInt32(_config["_implicitWaitTimeSpan"]));
        }

        public void Dispose()
        {
            _browserDriver.Quit();
        }

        [Fact]
        public void Should_Send_Email()
        {
            // Navigate and launch the Gmail URL
            _browserDriver.Navigate().GoToUrl("https://mail.google.com/");
            _browserDriver.Manage().Window.Maximize();

            // Enter the Username
            IWebElement userElement = _browserDriver.FindElement(By.Id(_config["_objectUserNameTextBox"]));
            userElement.SendKeys(_config["username"]);

            // Click on the Next Button
            _browserDriver.FindElement(By.Id(_config["_objectUserNameNextButton"])).Click();

            // Enter the Password
            IWebElement passwordElement = _browserDriver.FindElement(By.Name(_config["_objectPasswordTextBox"]));
            if (passwordElement.Displayed && passwordElement.Enabled)
                passwordElement.Click();

            passwordElement.SendKeys(_config["password"]);

            // Click on the Next Button
            _browserDriver.FindElement(By.Id(_config["_objectUserPasswordNextButton"])).Click();

            // Click on the Compose Button
            IWebElement composeElement = _browserDriver.FindElement(By.XPath(_config["_objectComposeButton"]));
            composeElement.Click();

            // Enter the Recipient's Email Address
            IWebElement toElement = _browserDriver.FindElement(By.Name(_config["_objectToTextBox"]));
            toElement.Clear();
            toElement.SendKeys($"{_config["username"]}@gmail.com");

            // Enter the Subject Line with Unique Date Time Stamp
            IWebElement subjectTextElement = _browserDriver.FindElement(By.Name(_config["objectSubjectTextBox"]));
            subjectTextElement.Clear();
            string subjectLineText = "Autogenerated Crossover Test User Email generated at " + DateTime.UtcNow.ToString();
            subjectTextElement.SendKeys(subjectLineText);

            // Enter the mail body text.
            string mailBodyText = "This is an Auto Generated Test Email.";
            IWebElement mailBodyElement = _browserDriver.FindElement(By.XPath(_config["objectMailBodyTextBox"]));
            mailBodyElement.Clear();
            mailBodyElement.SendKeys(mailBodyText);

            // Click on the More Options Button
            IWebElement moreOptionsElement = _browserDriver.FindElement(By.XPath(_config["objectMoreOptionsButton"]));
            moreOptionsElement.Click();

            // Click on the Labels Menu Item
            IWebElement labelMenuItemElement = _browserDriver.FindElement(By.XPath(_config["objectLabelMenuItem"]));
            labelMenuItemElement.Click();

            // Click and Add 'Social' Label to the Email
            IWebElement socialLabelElement = _browserDriver.FindElement(By.XPath(_config["objectSocialLabelMenuItem"]));
            socialLabelElement.Click();

            // Add Attachment to the Mail
            _browserDriver.FindElement(By.XPath(_config["objectAttachFilesButton"])).Click();

            System.Threading.Thread.Sleep(5000);
            FileUpload(_config["_filePath"]);

            // Click on the Send Mail Button
            IWebElement sendButtonElement = _browserDriver.FindElement(By.XPath(_config["_objectSendMailButton"]));
            sendButtonElement.Click();

            // Validate and Click on the Message Sent Link Text
            IWebElement _messageSentLink = _browserDriver.FindElement(By.CssSelector(_config["_objectMessageSentLink"]));
            Assert.True(_messageSentLink.Text == "View message");
            _messageSentLink.Click();

            // Validate the sent mail's Sender Name.
            string _mailFromText = _browserDriver.FindElement(By.CssSelector(_config["_objectVerifyMailSenderText"])).Text;
            Assert.True(_mailFromText == "User Crossover");
        }

        public void FileUpload(string filePath)
        {
            AutoItX3 autoItX = new AutoItX3();
            autoItX.WinActivate("Open");
            autoItX.Send(filePath);
            System.Threading.Thread.Sleep(2000);
            autoItX.Send("{ENTER}");
        }
    }
}